export { HomePage } from "./HomePage";
export { AboutPage } from "./AboutPage";
export { ServicesPage } from "./ServicesPage";
export { ProductsPage } from "./ProductsPage";
export { ProductDetailPage } from "./ProductDetailPage";
export { PortfolioPage } from "./PortfolioPage";
export { ProcessPage } from "./ProcessPage";
export { TeamPage } from "./TeamPage";
export { ContactPage } from "./ContactPage";
