import {
  Rocket,
  Shield,
  Lightbulb,
  Handshake,
  Zap,
  Telescope,
  Gem,
  Server,
  Wrench,
  Building2,
  Briefcase,
  Smartphone,
  TrendingUp,
  Mail,
  MapPin,
  Clock,
  CheckCircle,
  Award,
  GitBranch,
  Lock,
  Network,
  Brain,
  Blocks,
  Globe,
  Users,
  Store,
  Calculator,
  GraduationCap,
  Truck,
  UtensilsCrossed,
  Car,
  Coins,
  Search,
  Monitor,
  CreditCard,
  ParkingCircle,
  Camera,
  Wallet,
  Send,
  Hospital,
  Stethoscope,
  FileText,
  Calendar,
  ClipboardList,
  type LucideProps,
} from "lucide-react";

const iconMap = {
  rocket: Rocket,
  shield: Shield,
  lightbulb: Lightbulb,
  handshake: Handshake,
  zap: Zap,
  telescope: Telescope,
  gem: Gem,
  server: Server,
  wrench: Wrench,
  "building-2": Building2,
  briefcase: Briefcase,
  smartphone: Smartphone,
  "trending-up": TrendingUp,
  mail: Mail,
  "map-pin": MapPin,
  clock: Clock,
  check: CheckCircle,
  award: Award,
  "git-branch": GitBranch,
  lock: Lock,
  network: Network,
  brain: Brain,
  blocks: Blocks,
  globe: Globe,
  users: Users,
  store: Store,
  calculator: Calculator,
  "graduation-cap": GraduationCap,
  truck: Truck,
  "utensils-crossed": UtensilsCrossed,
  car: Car,
  coins: Coins,
  search: Search,
  monitor: Monitor,
  "credit-card": CreditCard,
  "parking-circle": ParkingCircle,
  camera: Camera,
  wallet: Wallet,
  send: Send,
  hospital: Hospital,
  stethoscope: Stethoscope,
  "file-text": FileText,
  calendar: Calendar,
  "clipboard-list": ClipboardList,
} as const;

export type IconName = keyof typeof iconMap;

interface IconProps extends LucideProps {
  name: IconName;
}

export const Icon = ({ name, ...props }: IconProps) => {
  const IconComponent = iconMap[name];
  return <IconComponent {...props} />;
};
